### ISSUE TITLE
Bugged quests on "Lunar festival " event.

### ISSUE THREAD

**Issue by Bug-finder** [LightsHope/issues#4]
1. Lunar Fireworks (http://vanillawowdb.com/?quest=8867)
If you get this quest and shoot 8 Fireworks and 2 Clusters you cannot complite it (None of the fireworks are counted for the quest)

2. Elune's Blessing (http://vanillawowdb.com/?quest=8868)
OMEN is not summoned for what you did not do. (See comment from link how its should)

3. https://forum.lightshope.org/viewtopic.php?f=6&t=10434

**Comment by brotalnia** [comment]
All issues fixed in https://github.com/ratkosrb/server/commit/7f42490ab33c06f45404089c0e483d0ffd478abd

**Comment by Bug-finder** [comment]
Did you fix this: http://web.archive.org/web/20060827062337/http://wow.allakhazam.com:80/db/item.html?witem=21746 ? "For every Elder you find, they send out one of these, each one contains a lucky rocket or a stone that shines light on an area... The lucky rocket gives you a buff that give +250 health which stacks with PW:F"         
Till we have no Lucky Red Envelope...

**Comment by Bug-finder** [comment]
Lunar Fireworks (http://vanillawowdb.com/?quest=8867) still not working.

**Comment by Bug-finder** [comment]
BUMP !! 
Lunar Fireworks (http://vanillawowdb.com/?quest=8867) still not working. !!!!!!!

**Comment by Bug-finder** [comment]
.
