### ISSUE TITLE
Piercing howl is bugged and is only applying to 1 target

### ISSUE THREAD

**Issue by trevorjk** [LightsHope/issues#604]
Piercing howl is bugged and is only applying to 1 target, it is supposed to affect all targets nearby. Started after Wednesday's patch i believe.

**Comment by mecher529** [comment]
can confirm

**Comment by karatequin** [comment]
This is game breaking please fix!!

**Comment by Omarthegreatone** [comment]
As a rogue I like it this way.

**Comment by Moonanite** [comment]
Can also confirm that Piercing Howl only works on a single target, despite the number of mobs. Ability appears to show visual cue that it has hit the target (target was in range and did not resist), however, it does not apply the slow or the debuff icon to the target. Mobs that ive tested this on include scorpids in southern barrens (Egg Hunt Quest), and also the excavators and formen (Gann's Reclaimation).

**Comment by brotalnia** [comment]
Known issue and already fixed on development branch a week ago. You just have to wait until the fix is applied to live servers.

**Comment by ghost** [comment]
A whole month with a broken core mechanic for warrior PVP and its still not fixed...

**Comment by brotalnia** [comment]
https://github.com/lh-server/core/commit/b301104921fdb1fa2905ae6c889e1c4bb0282cf9

**Comment by femdead** [comment]
it didn't get fixed in today's update?

**Comment by ghost** [comment]
Nope still broken. Only slows the one you have targeted even after todays reset.

**Comment by nacsdale** [comment]
FIX IT JESUS FU CKING CHREST

**Comment by ghost** [comment]
Any update on this? Getting a little ridiculous on how long its taking to fix. something this important.

**Comment by simonmathay** [comment]
Can confirm, really annoying!

**Comment by Godmatik** [comment]
Is this fix coming in Wednesday's update?

**Comment by ghost** [comment]
Guess not @Godmatik
